### ISSUE TITLE
Assistance editing GAN for different image set

### ISSUE THREAD

**Issue by vinaysp** [pavitrakumar78/Anime-Face-GAN-Keras#1]
Hi @pavitrakumar78,

I wanted to get in touch to see if you could possibly assist with an issue I am having. I am using your GAN_training.py to see if it can be applied to a different image set. The dimensions of the image are 3232x208. The images themselves are of video game level. As such I tried to change your code in the GAN_training.py so that it could use the game levels images as inputs. I also wish to output the generated images from the GAN as single images and not as 4x4 images as your code does.

 Please see screenshots attached that indicate areas where I have changed your code. 
Screenshot 1 - I have changed the figsize and gridspec size to 1x1
<img width="653" alt="screenshot1" src="https://user-images.githubusercontent.com/32655933/41971732-5c470dc0-7a07-11e8-9aab-77c2e5f45f4c.png">

screenshot2 - changed the image shape to 3232x208, the shape of the images i am trying to use as 
                        well as batch size and number of steps.
<img width="577" alt="screenshot2" src="https://user-images.githubusercontent.com/32655933/41971741-660f5704-7a07-11e8-99bb-2d4d074c027f.png">

screenshot3 -  changed the image_shape in the GAN_Nets.py file for get_disc_normal function
<img width="437" alt="screenshot3" src="https://user-images.githubusercontent.com/32655933/41971789-8b4b683c-7a07-11e8-9d27-de93575b4072.png">

screenshot4 - error message i receive when running the GAN_training.py 
<img width="655" alt="screenshot4" src="https://user-images.githubusercontent.com/32655933/41971837-ad77847c-7a07-11e8-8063-8c93279c2389.png">

I would really appreciate your help, or any guidance you can give me as to how to resolve the issue shown in screenshot 4. Please let me know if you need anymore information.

Thanks.

**Comment by pavitrakumar78** [comment]
Are you sure the image you open at line [57](https://github.com/pavitrakumar78/Anime-Face-GAN-Keras/blob/master/GAN_Trainingv3.py#L57) is of shape (3232,208,3)? Try opening an image separately and check the dimensions. The error has nothing to do with any code that you have attached above. `image_shape` which is a parameter to `sample_from_dataset()` function should match the dimensions of whatever image you are loading.

**Comment by vinaysp** [comment]
@pavitrakumar78 I have previously checked the size of the images and am certain the dimensions I have provided above are correct, these images are images of actual 2d platformer game levels.

You mention that the error is not to do with the code? what does the error in screenshot refer to?Apologies but I am still pretty new to GAN models

**Comment by pavitrakumar78** [comment]
It does where the images are from and the error has nothing to do with GAN logic. It's just that the image you inputted is of shape (208,3232,3) and when you try to save it into an array of objects of shape (3232,208,3) it gives you the error you see above.  
Try changing line 66 to:
`sample[index,...] = image.T`

**Comment by vinaysp** [comment]
<img width="563" alt="screen shot 2018-06-27 at 15 21 36" src="https://user-images.githubusercontent.com/32655933/41980525-991f6294-7a1e-11e8-90a2-a82742c36b4e.png">
@pavitrakumar78 When I changed the line to   sample[index,...] = image.T  the above error occurred

I then tried the following   sample[index,...] = image.T[2,1,0]   I got the following error
<img width="562" alt="screen shot 2018-06-27 at 15 29 29" src="https://user-images.githubusercontent.com/32655933/41980672-f136b05e-7a1e-11e8-9343-fc066f871e55.png">

**Comment by pavitrakumar78** [comment]
Sorry. My bad, use `np.rot90(image)` instead of `image.T` because it's a 3D array.

**Comment by vinaysp** [comment]
still producing index out of range error
<img width="567" alt="screen shot 2018-06-27 at 15 54 54" src="https://user-images.githubusercontent.com/32655933/41982120-861d6dd6-7a22-11e8-83f9-ca634f3971f7.png">

**Comment by pavitrakumar78** [comment]
Please check where the error is coming from and work from there. The original error you had has been solved.  

If you need help with matplotlib, check their [documentation](https://matplotlib.org/contents.html).   

Since this is not an issue anymore with the actual code in the repository, I will close this issue. If you think there is still an issue related to the code (like GAN logic), feel free to re-open this issue.
