### ISSUE TITLE
Generating the refined image

### ISSUE THREAD

**Issue by psychedelic2007** [pavitrakumar78/Anime-Face-GAN-Keras#2]
Hey Pavitra,

Really loved your implementation of Anime Face GAN. I just had one minor doubt. I am new in the field of ML. So I was wondering that since the dataset consists of around 1000 images, our output generated in the jupyter notebook codes shows only 16 images (maybe just a glimpse of some images). But how can I generate/recreate the rest of the images? Like do I need to upload the image with a new python code in a fresh jupyter notebook and then again train my model on that single image? I would really appreciate it if you can help me out with this.

**Comment by pavitrakumar78** [comment]
You can generate as many images as you want.
Check out:
https://github.com/pavitrakumar78/Anime-Face-GAN-Keras/blob/master/GAN_Trainingv3.py#L100
and
https://github.com/pavitrakumar78/Anime-Face-GAN-Keras/blob/master/GAN_Trainingv3.py#L75

You generate noise (batch size 64), pass it into the generator and the function picks images at random from the 64 images.
